= Red Hat OpenShift Application Runtimes - Spring Boot Training
Thomas Qvarnstrom and Greg Hoelzer

:sectnums!:
:toc: left
:revnumber: 1.1
:revdate: 2017-10-13

This repository is the used to develop training materials for Red Hat OpenShift Application Runtimes. This module/lab focuses on https://projects.spring.io/spring-boot/[Spring Boot]. The main authors of _{doctitle}_ are *{author}*, Red Hat and the current version ({revnumber}) was last updated on {revdate}.

== Lab Overview

[cols="1,4", options="header"]
|===
2+|  Details
| Technology/Product | Red Hat OpenShift Application Runtimes, Spring Boot
| Difficulty | 3
| Time | 3 hours
| Prerequisites | An understanding of Java application development and familiarity with OpenShift and Linux Containers
|===


== Introduction

This is a lab aimed at enabling JavaEE developers using Spring Boot, common frameworks and Microservices architecture to build, deploy and test their components on the OpenShift Container Application platform.  

*Clone this repo into a local working directory if you wish to perform the lab excersises*

Here is a short list for the available exercises:

* link:lab/docs/lab1-instructions.adoc[Lab 1 - How to use Spring Boot on RHOAR and OpenShift]
* link:lab/docs/lab2-instructions.adoc[Lab 2 - Create and Execute Jenkins 2.0 Build Pipeline]
