:noaudio:
:scrollbar:
:data-uri:
:toc2:

== Lab 2 - Creating an OpenShift Application Build Pipeline

In this lab, you will learn how to create a Jenkins 2.0 Build Pipeline for our spring application using a Maven Binary/S2I build. We enable the Pipeline to Deploy the App, Smoke Test it, and introduce a Manual Step to Tag the created Container Imagestream for Release.

:numbered:

== Fixing product-catalog Deployment Configuration

In this step, we will update the initially created Deployment Configuration, to enable our Build Pipeline to control application deployment:

1. From the OpenShift Web Console, select the *product-catalog* Deployment
2. Under the *Actions* Drop Down on the upper right, select *Edit*
3. Scroll down to the *Images* section, *uncheck* both options that *automatically start new deployments*

== Creating product-catalog Build Pipeline

In this step, we will create and update our Build Pipeline, deploying a Jenkins 2.0 instance into our OpenShift project:

1. From command line and where this project was cloned, navigate to the */lab/.openshift* directory
2. Ensure you are logged into OpenShift and your Lab Project, then execute the following *oc* command:
+
[source,bash]
----
*oc create -f mvnBinaryBuild.yaml*
----
+
3. You shoud see the message *buildconfig "product-catalog-mvn-pipeline" created* if the command was successful
4. From the OpenShift Web Console, under *Other Resources*, you should now see that a *Jenkins* deployment was created and in the process of starting up:
+
Once started, verify you can login to your Jenkins instance via the created Route using your OpenShift Credentials
Select and review the Jenkins Pipeline Job created, and DSL for our Pipeline.
+
5. From the OpenShift Web Console, select *Builds* then *Pipelines*, then our newly created *product-catalog-mvn-pipeline*
+
Under the *Actions* Drop Down on the upper right select *Edit*
+
