apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "product-catalog", "namespace": "",
      "kind": "DeploymentConfig"}]'
  labels:
    name: product-catalog-mvn-pipeline
  name: product-catalog-mvn-pipeline
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |
        try {
           timeout(time: 20, unit: 'MINUTES') {
              def appName="product-catalog"
              def project=""

              node {
                stage("Initialize") {
                  project = "product-catalog-demo"
                }
              }

              node("maven") {
                stage("Checkout") {
                  git url: "https://github.com/jimgarrett123/ocp-rhoar-spring.git", branch: "master"
                }

                stage("Build Spring Boot JAR") {
                  sh "mvn clean package -Popenshift --file lab/pom.xml"
                  stash name:"jar", includes:"lab/target/product-catalog.jar"
                }
              }

              node {
                stage("Deploy") {
                  openshiftDeploy deploymentConfig: "product-catalog"
                }
                stage("Smoke Test") {
                  sh 'curl http://product-catalog-spring-rhoar-lab01.cloudapps.keyvan.com/admin/productlist | grep -i "Admin - Product List"'
                }
              }
           }
        } catch (err) {
           echo "in catch block"
           echo "Caught: ${err}"
           currentBuild.result = 'FAILURE'
           throw err
        }
        node {
          stage("Tag and Release Image") {
            input "Promote next Release"
            openshiftTag alias: 'false', apiURL: '', authToken: '', destStream: 'product-catalog', destTag: 'next-release', destinationAuthToken: '', destinationNamespace: '', namespace: '', srcStream: 'product-catalog', srcTag: 'latest', verbose: 'false'
          }
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
